### ISSUE TITLE
PepLand license

### ISSUE THREAD

**Issue by mgarort** [zhangruochi/pepland#2]
Dear PepLand team,

Thank you for publishing your pre-print and code! I think this is a great approach to model peptides with non-canonical amino acids.

I am interested in using your code and pre-trained models. However, I cannot find the license file in the repository. What is the license of the code and model? Are you releasing them under a free license like MIT or Apache?

Thanks in advance,
Miguel

**Comment by zhangruochi** [comment]
> Dear PepLand team,
> 
> Thank you for publishing your pre-print and code! I think this is a great approach to model peptides with non-canonical amino acids.
> 
> I am interested in using your code and pre-trained models. However, I cannot find the license file in the repository. What is the license of the code and model? Are you releasing them under a free license like MIT or Apache?
> 
> Thanks in advance, Miguel

Hi Miguel,

Thank you for your interest in our work. I have already update the LICENSE file in the repository. If you have any other question, please reach out to me.

Best, 
Richard.

**Comment by mgarort** [comment]
Great, thanks a lot!

Closing this issue now.
